### ISSUE TITLE
What is process to add package to conda env?

### ISSUE THREAD

**Issue by tnguyensanger** [malariagen/agam-report-base#16]
@alimanfoo    We occasionally need to query MySQL databases in the vector-ops production notebooks.  This requires the MySQLdb python package, which can be installed like so:

conda install -c bioconda mysqlclient

(as per https://stackoverflow.com/questions/34140472/how-can-i-use-conda-to-install-mysqldb)

Should we create a separate vector-ops production conda environment?  Or simply add packages as necessary to the agam-report-base/install/conda.txt environment package list?

**Comment by alimanfoo** [comment]
I think would be good to add the dependency to conda.txt, it will help when
I or someone else wants to query a mysqldb like fits. PR here welcome.

**Comment by tnguyensanger** [comment]
I seem to have trouble pushing a branch.  Do I have write permissions to this repo?  Should I fork instead?

**Comment by alimanfoo** [comment]
Yes fork is easiest and best way for public repos, thanks.
